### ISSUE TITLE
Polygons in enlarged topos not displayed correctly

### ISSUE THREAD

**Issue by birgander2** [theCrag/tca#1]
When I select the "topo" tab, the routes are displayed correctly. But  after clicking on the "enlarge" button, it seems the polygons are not interpreted anymore and I see only straight lines from anchor point to anchor point.

**Comment by rouletout** [comment]
@birgander2 can you please post a screenshot (once it works) for this one? Thanks!

**Comment by birgander2** [comment]
Took me a while to find out how to make screenshots on Android. However: "this app does not allow to take screenshots!".

**Comment by andrasbari** [comment]
We will fix it.
We allowed to take screenshots since version 3.0.47

**Comment by birgander2** [comment]
I have that version, but I'm sorry, I can't  take a screenshot while being in "zoomed topo mode". However, in the normal "topo tab" it works, strange.

**Comment by rouletout** [comment]
Fixed with next release
