### ISSUE TITLE
Unify route count style

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#101]
**What happened?**
The website has a circle and route count number inside.
The app has the donut but no route count inside. Instead it uses a map symbol(?) to show the route count.

Please, align this.

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
Left - website; Right - app
![image](https://user-images.githubusercontent.com/30682796/114926503-b52a5000-9e30-11eb-9f68-774718ed9e2c.png)

**What you expected:**

* [ ] App follows website

**Comment by rouletout** [comment]
Move the donut down into the white bar (next to number) to avoid background color interference
