### ISSUE TITLE
Random grade icon size on Search list

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#104]
**What happened?**
On the route list on the search page the grade icons seem to have random size. They should all have the same size

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/114933565-181fe500-9e39-11eb-8100-b01682aef9c5.png)

**What you expected:**

* [ ] Grade icons have constant size
* [x] Icons are not black

**Comment by rouletout** [comment]
Will be fixed

**Comment by rouletout** [comment]
Constant size would waste too much space considering slash grades and protection ratings - closing
