### ISSUE TITLE
App crash on opening a specific sector

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#107]
**What happened?**

Go to https://www.thecrag.com/en/climbing/spain/alto-mijares/hoz-del-mijares/area/806165931 and from there open "Obras Selectas" (https://www.thecrag.com/en/climbing/spain/alto-mijares/hoz-del-mijares/area/806165931) - the app crashes

Ideally also provide screenshots:

**What you expected:**

The sector opens

**Comment by nicHoch** [comment]
this sector contains a "very large" topo image: https://www.thecrag.com/topo/1489100907
maybe that is the reason

**Comment by andrasbari** [comment]
The crash caused by the 16th route. I fixed it. The 16th route did not have a grade. The coloring of the grade "bubble" caused the crash. I have fixed it.
