### ISSUE TITLE
Search: display results without selection click

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#109]
**What happened?**

For both, local and global search it would be nice to see results and not just the small numbers next to the type of results.

Ideally also provide screenshots:

**What you expected:**

If I search local it is most likely one sector or route I find, or a couple, list them directly so the user sees a result. Even knowing that the results are reflected by the small numbers I sometimes miss that the search is done and that there are results.

Same logic could apply globally....

**Comment by bkucsera** [comment]
Done, we always display a search result - if the search finds anything.

**Comment by rouletout** [comment]
This looks much better :-) - closing - the issue we found with Frenesi and Frenesí is still there - i add it to another issue
