### ISSUE TITLE
Back button does not work

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#11]
Opening a sub-area from an area (eg Rotkopf from Zillertal) and clicking the device back button does not send you back to Zillertal. Instead nothing happens.

**Comment by bkucsera** [comment]
You choose Rotkopf from the list menu i guess. Please confirm it. 
The back button is working for us on our devices. If you can repeat the problem, can you please send a short video of it?
(Maybe the problem reason can be the tablet, we have to see if it works differently or not.)

**Comment by rouletout** [comment]
Yes this is correct, I chose Rotkopf. This still happens. It is quite weird as the backlighting of both buttons (back and app screens) goes on but nothing happens.

**Comment by rouletout** [comment]
Here the video for trying to open Rotkopf: https://www.dropbox.com/s/k1wd0zi3stk64j8/IMG_7128.MOV?dl=0

And here the video with the failing back button: ﻿https://www.dropbox.com/s/7wjkuajpwzow6oj/IMG_7129.MOV?dl=0

**Comment by rouletout** [comment]
Seems to work now, closing
