### ISSUE TITLE
Offline Download Button missing

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#114]
**What happened?**

Supporter only function disappeared somehow...

Ideally also provide screenshots:

**What you expected:**

Download button available

**Comment by bkucsera** [comment]
It was removed with the share button accidentaly, we put it back.
Other issues in this topic continued in #115 .

**Comment by bkucsera** [comment]
Fixed.

**Comment by rouletout** [comment]
Button is here but see https://github.com/theCrag/tca/issues/115 for follow-up issues - closing this one.
