### ISSUE TITLE
Offline mode functionality

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#115]
Non-supporters:
- topos not available
- map and crag descriptiopn available if visitied before
- download button avaialable but leads to donation page via explanation screens

Supporters & subscribers:
- Have download for offline use functionality (button)

**Comment by bkucsera** [comment]
Fixed, please check.

**Comment by rouletout** [comment]
Button is there but I get a pop-up that asks me to become a pro member....

Also, if I click not interested the app goes "white" with just the top status bar available but not responsive, have to re-start.

**Comment by bkucsera** [comment]
I have added a subscription for you, now you will have to be able to download topos. (As we discussed, the automated subscription for TC supporters will be in the later release, until that we can add manually.)

For us, the "Not interested" button works well. Can you please check again?

**Comment by killakalle** [comment]
@bkucsera also seeing the membership popup

![Screenshot_20210512_235821_com topoguru](https://user-images.githubusercontent.com/30682796/118049753-81364200-b37e-11eb-9248-207cc61dfba1.jpg)

I'm a theCrag supporter. Could you give me a subscription, please?

**Comment by bkucsera** [comment]
added! please go to your profile page and update with swiping down.

**Comment by killakalle** [comment]
works, thank you!

**Comment by rouletout** [comment]
closing
