### ISSUE TITLE
Crag not found in search

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#116]
**What happened?**

1. Search for "lliria"
2. See that there are no search results

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/area/3841337841

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/116793850-8d421a00-aac9-11eb-98e5-dede9e352069.png)

![image](https://user-images.githubusercontent.com/30682796/116793855-9501be80-aac9-11eb-8a16-d9098544f931.png)

![image](https://user-images.githubusercontent.com/30682796/116793946-148f8d80-aaca-11eb-9e0e-59b8a2b41c24.png)

**What you expected:**

* [ ] Lliria shown in search results

**Comment by rouletout** [comment]
@bkucsera can you assess if this is a bug or limited functionality?

**Comment by rouletout** [comment]
I assume this is the same issue we had identified for routes in "Jilotepec". We were searching for "Frenesi" and we found one sector and one route. The sector is displayed but the route not - both are written as "Frenesí" (Spanish i).

**Comment by rouletout** [comment]
Closing in favor of https://github.com/theCrag/tca/issues/161
