### ISSUE TITLE
Crag Map: Overlay of Donuts and polygon results in misleading colors

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#12]
Opening the Crag map shows "purple" donuts instead of blue ones for exmaple in "Ewige Jagdgründe" in Zillertal.

**Comment by bkucsera** [comment]
On the crag overview map we use blurred donuts, to solve the problem of visibility, of some donuts are covering each other. 
We will change this and there will be no blurring, so the original colours will be shown on the crag map also.

**Comment by rouletout** [comment]
This seems solved, closing
