### ISSUE TITLE
Inconsistent tab order

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#120]
**What happened?**
I've seen more than one order of tabs in use

- Info - Areas - Search
- Info - Search - Areas

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/117069669-11e0a280-ad2d-11eb-9110-e7104f2678e1.png)

![image](https://user-images.githubusercontent.com/30682796/117069701-1ad17400-ad2d-11eb-9490-36ec0cebc7ba.png)

**What you expected:**

* [ ] Info - Areas - Search
* [ ] Consistency

**Comment by rouletout** [comment]
Fixed, closing
