### ISSUE TITLE
Offline Download for non-supporters

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#122]
**What happened?**

If I'm not a supporter the "Whoops!" pop-up refers to PRO memebrs and not to the theCrag Supporter Page.

The following pop-ups / guides should be different for either directing to TopoGuru Pro or Supporters.

Ideally also provide screenshots:

**What you expected:**

See above

**Comment by killakalle** [comment]
More nun-supporters ... ;-)
![image](https://user-images.githubusercontent.com/30682796/117371726-a92e2d00-aec8-11eb-84ca-b87e4507e5c6.png)

**Comment by rouletout** [comment]
Now the goal is to make them, all supporters :-)

**Comment by rouletout** [comment]
Due to legal reasons this has to be done within the app - for now at least. Closing.
