### ISSUE TITLE
Cannot navigate to crag

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#125]
**What happened?**
I would like to get maps navigation to a crag. The crag has a location but not topos. I'm not able to start navigation.

The solution chosen in https://github.com/theCrag/tca/issues/77 does not solve the problem and has the following shortcomings:
- cannot navigate to a crag that does not have topos
- In addition, I don't think it's the right place to put the functionality to start navigation underneath each topo. For one, it's redundant and the space would be better used by displaying routes, two, that's not where I would look for it. I think it should be with the crag/sector info. e.g. when you click on the car icon on Info

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/castellon/area/2941493277

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/117477285-1d66e000-af5e-11eb-8503-dd337291e2b9.png)

**What you expected:**

* [ ] I can start maps navigation to a crag/sector/etc when it is located
* [ ] More intuitive place where a user would look for finding the navigation to a crag.

**Comment by rouletout** [comment]
Clicking on the car works now, closing

**Comment by killakalle** [comment]
@rouletout Clicking on the car does not do anything for me.

Android, version 4.0.13 (181)
