### ISSUE TITLE
Google login for The Crag Users.

### ISSUE THREAD

**Issue by Crazy-Pete** [theCrag/tca#127]
**What happened?**
Since creating my account on the crag I have used the login with Google button, as a result I never set a password with the crag. 
When attempting to login to the app, there is no option to login with Google.  Instead, I had to reset my password at thecrag.com, go back to the app, then sign-in with my email and new password. 

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![Screenshot_20210511_075200_com topoguru](https://user-images.githubusercontent.com/83996523/117839081-baac6780-b22f-11eb-98ad-e57483a35542.jpg)

![Screenshot_20210511_075206_com topoguru](https://user-images.githubusercontent.com/83996523/117839090-bd0ec180-b22f-11eb-8039-d18f62c281c2.jpg)

The Crag.com: 
![Screenshot_20210511_080250_com android chrome](https://user-images.githubusercontent.com/83996523/117839110-c1d37580-b22f-11eb-850e-2d373ef0fb01.jpg)

**What you expected:**

* The same options to login that are available on TheCrag.com

**Comment by rouletout** [comment]
This is a technical limitation that we can not work around - you need to know your password to login using theCrag account. Closing.
