### ISSUE TITLE
Crag Map: Zooming out does not show nearby crags

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#13]
Zooming out from the crag map does not show any nearby crags giving the impression that there are none.

**Comment by bkucsera** [comment]
We will fix this later, when the World Map issue will be finalised. 
(We have to copy the code from there, until the World Map is under development, we havent done it.)

**Comment by rouletout** [comment]
This is still the same

**Comment by bkucsera** [comment]
Solved, please check it.

**Comment by rouletout** [comment]
Works, closing
