### ISSUE TITLE
iOS: formatting of headings for descriptive sections

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#130]
**What happened?**

The headings look like regular text and have no vertical separation.

![image](https://user-images.githubusercontent.com/19162952/122654231-a8b3c380-d10f-11eb-90cd-a05c0b63aaff.png)

**What you expected:**

* [ ] heading with separate format
* [ ] space before and after
* [ ] top description header can be eliminated

**Comment by bkucsera** [comment]
Fixed.
