### ISSUE TITLE
iOS: distance info not consistent

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#131]
**What happened?**

The overview screen gives a different distance to the crag than when you open it on the map, see screenshots as example (234m versus 6.58km)

![image](https://user-images.githubusercontent.com/19162952/123145807-d4da8780-d422-11eb-92ab-f182b1b4c43f.png)

![image](https://user-images.githubusercontent.com/19162952/123146311-56cab080-d423-11eb-8378-380fb2e0127f.png)
**What you expected:**

Same and correct distance info

**Comment by bkucsera** [comment]
Do you still have the problem?
Can you please try with another crag as well?
Im testing now and every crag shows the same distance for me.

**Comment by rouletout** [comment]
yes this is still  the same, also with other crags but not all, see this example (2 screenshots):


![IMG_7746](https://user-images.githubusercontent.com/19162952/124799714-76310580-df1a-11eb-99d1-9cd127418de5.PNG)


![IMG_7745](https://user-images.githubusercontent.com/19162952/124799764-82b55e00-df1a-11eb-870c-fc50bac909a7.PNG)

**Comment by rouletout** [comment]
the last few times I checked this was gonbe, i close it for now
