### ISSUE TITLE
iOS: Slash grades not displayed correctly

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#133]
**What happened?**

For example here:  https://www.thecrag.com/de/klettern/mexico/area/2682816909 there is a route (number 11) that has a grade of 5.12a/b but it is displayed as 5.12a. The color coding is correct but the grade is wrong.

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/19162952/123147720-fd638100-d424-11eb-92ca-98d7b84d69d0.png)

**What you expected:**

Correct display of slash grades.

**Comment by rouletout** [comment]
I raised that to fix for next release as it gives wrong grade info - @bkucsera

**Comment by bkucsera** [comment]
As discussed before, we do it in the next live release, together with android.

**Comment by bkucsera** [comment]
Here is a solution-suggest, please review the idea:
- we show the slash grades in the route list, if it is maximum 2 characters longer than the original grade. Example: 5.13c/d --> we show this on the route list.
- if the slash grade is more than 2 characters longer than the normal grading (eg: 5.13d/5.14a), we just show the primary grade ON the route list screen. AND we show the whole slash grade on the route info page (when you click on a route)

This way we do not loose to much on UX, with too long grades.
What do you think, is it a good solution? Any other ideas? @rouletout

**Comment by rouletout** [comment]
I think acceptable even though it is not the best way to inform a user about a grade - can we add 3 dots to a slash that is too long so that it is clear that there is more to it?

**Comment by bkucsera** [comment]
So add 3 dots in every time when it is a slash grade? Or just in those cases, when it would be longer than 2 characters?
By the way we can decide to show the slash grades in every cases, independently of how long is it. But in this case the route name can be cut. 

In those cases when we cut the route name because its longer than the available space, we will make rolling route names on iOS as well, as we have it on android now.

**Comment by rouletout** [comment]
I would just do it if we can't put the full slash grade. Displaying grades correctly is "safety critical" so we are pretty careful with that in general. I think the grade is more important than the full name :-) - so if you can do thge rolling anme even better...

**Comment by bkucsera** [comment]
Slash grades fixed, please check.

**Comment by rouletout** [comment]
Looks good, closing
