### ISSUE TITLE
iOS: map loads endlessly

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#138]
**What happened?**

Opening the app in flight mode the map is not responsive but seems to load endlessly.

Switching to search and other functions work.

![image](https://user-images.githubusercontent.com/19162952/123856502-c7bc0d80-d8e6-11eb-8eea-6ce1117c1e11.png)

**What you expected:**

Load map, allow to center on current location.

**Comment by bkucsera** [comment]
Fixed, please check.
