### ISSUE TITLE
Login with theCrag shows red status bar

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#141]
Login with theCrag shows red status bar

![IMG_7718](https://user-images.githubusercontent.com/19162952/124359818-33a2bc80-dbec-11eb-8c06-34b2b2034815.PNG)

**What you expected:**

No status bar as this might confuse users

**Comment by bkucsera** [comment]
This seems to be a system message from thecrag.com, as this is the login page of the website. Can you check this please with Simon?

**Comment by scd** [comment]
The message will be there if you are on sandpit. Can you please provide the
url that makes this happen?

**Comment by rouletout** [comment]
It is this URL: https://www.thecrag.com/oauth/authorize?oauth_token=02aesevc297u0p7u

@scd

**Comment by scd** [comment]
@rouletout this should be fixed now. Can you please login and verify.

**Comment by rouletout** [comment]
good now, closing
