### ISSUE TITLE
iOS: Map does not show areas on first opening

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#142]
After a fresh install of the app (old one deleted) when opening the map and going to current location the clsuers do NOT open up (see screenshot, it still shows San Cristobal while I'm zoomed in to see all crags In the area). Zooming in and out does not help. You need to open San Cristobal and go back to the map so that the crags are shown.

![IMG_7719](https://user-images.githubusercontent.com/19162952/124359885-76649480-dbec-11eb-8e67-a7f6d22d8569.PNG)

**What you expected:**

Show crags according to zoom level

**Comment by bkucsera** [comment]
Please check this with the latest version, now i did 2 clean installs and i always see the donuts. Thanks!

**Comment by rouletout** [comment]
@bkucsera still the same for me after deleting the app and new install

**Comment by rouletout** [comment]
@bkucsera also still the same with the latest release

**Comment by bkucsera** [comment]
In this issue the solution now is that you click on first "San Cristobal de las casas" donut, as you wrote. At the moment we download theCrag data until TLC level. If we would download one more level under, it were a much bigger amount of data to download at first opening. 
I suggest to keep it like this and we can get back to this issue later if we get more user concerns on it.

**Comment by rouletout** [comment]
close
