### ISSUE TITLE
iOS: Markup shown for Annotations

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#144]
In the route list the description for the annotation has a leading and trailing "<p>"

![IMG_7721](https://user-images.githubusercontent.com/19162952/124360027-1cb09a00-dbed-11eb-9d10-eb9dbc4af3b5.PNG)

What you expect:

Show plain text with formatting.

**Comment by bkucsera** [comment]
Fixed in the latest version: 4.0.3 (1)
