### ISSUE TITLE
Grades not consistent between app and web

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#145]
**What happened?**

Here https://www.thecrag.com/de/klettern/mexico/area/1730339028 the route https://www.thecrag.com/de/klettern/mexico/route/2659720725 is 10d but on the app 10c

Ideally also provide screenshots:

![image](https://user-images.githubusercontent.com/19162952/124639149-6dc0c800-de51-11eb-82b8-2eec874b6a92.png)

![image](https://user-images.githubusercontent.com/19162952/124639171-73b6a900-de51-11eb-878d-7fbc6c24952c.png)

**What you expected:**

Consistent grades

**Comment by bkucsera** [comment]
Fixed, please check. v 4.0.3 (3)
