### ISSUE TITLE
IOS: Topos not loaded after download

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#146]
**What happened?**

I downloaded all of San Cristobal anf got confirmation that I'm good to go, once offline the Topo images were not available.

![image](https://user-images.githubusercontent.com/19162952/124956866-113ee380-dfde-11eb-8146-9ebebabe1061.png)

Ideally also provide screenshots:

**What you expected:**

All content available offline

**Comment by bkucsera** [comment]
Can you please try to delete the app and reinstall, and then try again?
Now i downloaded for offline "San Cristobal", and i can see the topos of Cerro de don Lauro and Arcotete as well. (i did not open Arcotete before, so its not working from the cache, but from the offline downloaded content).

**Comment by rouletout** [comment]
Works on re install
