### ISSUE TITLE
iOS: map loads forever

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#147]
**What happened?**

Upon opening the app (not first time) the map seems to load forever even with network. Goto current position doesn't work, other functions do.

You can only use the bottom bar to get out of it.

![image](https://user-images.githubusercontent.com/19162952/124958114-6af3dd80-dfdf-11eb-9faf-6c20fda27ba0.png)

Ideally also provide screenshots:

**What you expected:**

No loading circle on map, responsive map.

**Comment by bkucsera** [comment]
Unlimited loading icon has been fixed.
On my device "find my position" button works, please check again on yours. If still not, please send a feedback.

**Comment by rouletout** [comment]
Still the same for me - map navigation is blocked on opening

**Comment by rouletout** [comment]
this is gone, closing
