### ISSUE TITLE
iOS: Follow the arrow not working

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#149]
**What happened?**

Clicking on Follow the arrow does not result in any action.

**What you expected:**

Not sure what the intended functionality is.

**Comment by bkucsera** [comment]
Follow the arrow shows you the direction of the selected topo, from your actual position. It has sense when you are navigating in the crag and looking for a boulder/wall.
You can also start a navigation there, with the icon on the right side.
Shall we add some function on the arrow?

**Comment by rouletout** [comment]
Ok but the arrow isn't turning for me when I turn the phone - this is the intended behavior, no?

**Comment by bkucsera** [comment]
Fixed. 
The problem occured when you were looking a TC content, then change to a TG content and later going back to TC part again. There was no new location ask, now we have, so it works.
