### ISSUE TITLE
Topos: wrong image shown

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#157]
**What happened?**

As an example in "Pena Maria" (Mexico) when opening the list of topos (see screenshot) the first image should show the area topo. The overlay seems correct but the image is wrong.

When opening the image, the correct image is shown (see screenshot)

This only happens when offline and content is downloaded - online the correct data are shown.

![IMG_7882](https://user-images.githubusercontent.com/19162952/128218968-7ba62c04-8561-4925-b22e-e1ea7266c008.PNG)

![IMG_7881](https://user-images.githubusercontent.com/19162952/128218939-f70c957a-d4c7-46a1-9a31-afedb0c9327f.PNG)

Ideally also provide screenshots:

**What you expected:**

Correct dispaly of topo images

**Comment by bkucsera** [comment]
Fixed in the latest version, please check.
Now you see the good topos in offline as well.

**Comment by rouletout** [comment]
Works, closing
