### ISSUE TITLE
Route Page - crticial info missing

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#158]
When opening a route page there is no info on number of bolts, quality, route history or structured tags for the route.

Ideally also provide screenshots:

**What you expected:**

All info items listed above shown.

- [ ] bolts
- [ ] quality
- [ ] route history
- [ ] structured tags on route level (might be there, not sure)

**Comment by bkucsera** [comment]
Missing info added to route page, please check.

**Comment by rouletout** [comment]
Looks good, closing
