### ISSUE TITLE
Search: seems to be stuck on repeated search terms

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#161]
Search seems to be stuck sometimes, especially on repeated searches. Checked together with Balint.

Examples used: Peña Rotja (with and without "ñ") and "lliria" and "Mautern"

See also: https://github.com/theCrag/tca/issues/116

Ideally also provide screenshots:

**What you expected:**

Search works

**Comment by bkucsera** [comment]
Search improved, please check and report if you still find problems. Thanks!

**Comment by rouletout** [comment]
I can't even enter a search term. Clicking on the magnifying glass does not open the keyboard.

**Comment by bkucsera** [comment]
Do you have the latest version installed on your device? We had a problem with this in a previous TestFlight version, but is has been fixed with the latest version. Please check.

**Comment by rouletout** [comment]
The latest from the app store, not testflight

**Comment by bkucsera** [comment]
Problem fixed, please check the latest live release.

**Comment by rouletout** [comment]
Search term can now be entered and the examples from above work now - closing
