### ISSUE TITLE
400 error accessing Donautal crag

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#17]
![Screenshot_20210126-180527.png](https://user-images.githubusercontent.com/1528540/105880137-485aa300-6003-11eb-939f-fd95a38ebbd6.png)

Got that several times accessing a crags description from the map.

**Comment by lordyavin** [comment]
Maybe correlated with #2

**Comment by rouletout** [comment]
Beta only works for Austria and Switzerland, closing
