### ISSUE TITLE
Read more on thecrag button does not work

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#18]
The button "read more on thecrag" does not work and the app crashes.

Addionally I was surprised to see such a button at all.

**Comment by rouletout** [comment]
Can you test that for an area in Austria or Switzerland please?

**Comment by lordyavin** [comment]
Did it. Does not work. Would upload a screen video but I don't have an app to record it.

**Comment by bkucsera** [comment]
Thanks for it! We have not activated this function yet, will do it soon. The button will link you to the browser app, directly on the selected area/crag/etc site on thecrag.com

**Comment by rouletout** [comment]
This works now, closing
