### ISSUE TITLE
What are "Premium Crags"

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#19]
What is the concept behind "Premium Crags"? I see that it is a premium feature of the app 

* but where are the data from?
* How should this incorporate with contributions made by the community?
* Will the website introduce this sort of pay wall too?
* Is this to fund the development of the app?
* Will the raised money support the maintenance and development of the website too?

**Comment by rouletout** [comment]
This is "legacy TopoGuru" content and aprt of the TopoGuru business model and has nothing to do with theCrag. It is very important to make clear that there is no intention to make users pay for content available on theCrag.

If and how we will separate premium content and free content is part of the ongoing discussion.

**Comment by rouletout** [comment]
Question answered, closing

**Comment by lordyavin** [comment]
The answer is not sufficient as long as you don't describe the concept how to implement a good solution.
