### ISSUE TITLE
App freezes on area select from map

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#2]
See screenshot: I clicked on the donut but open this screen but clciking on the white bar for Jassingau doesn't do anything. Also the back button on the device doesn't do anything. I can just pan and zoom the map and open another crag.

![IMG_7118](https://user-images.githubusercontent.com/19162952/105502748-d28aca80-5cd6-11eb-80fd-0b56d526e060.jpg)

**Comment by andrasbari** [comment]
Please share the full path for the crag. You can share the selected crag with the round greyed background link icon on the top right of the white bar.
You will got this link: http://thecrag.topoguru.com/map/941840751
Those links are only for testing and works only with the Topo Guru app. On regular browser gives HTTP 404 error.

**Comment by bkucsera** [comment]
@rouletout Can you do the bug again? We have checked this crag in the app and its working perfectly on our devices. Please try this once more and report if you still have this problem. Thanks!

**Comment by rouletout** [comment]
@bkucsera this is working now but I have to click the white bar like 5 times to open the crag details page

**Comment by rouletout** [comment]
A video for this behaviour can be found here: https://www.dropbox.com/s/maum2xhzlcazog8/IMG_7126.MOV?dl=0

**Comment by rouletout** [comment]
Also, once the crag opens, here the video for the crash using the back button: ﻿https://www.dropbox.com/s/149efi63d80sa7l/IMG_7127.MOV?dl=0

**Comment by rouletout** [comment]
Gone, closing
