### ISSUE TITLE
Why "TopoGuru powered by theCrag"

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#20]
Why "TopoGuru powered by theCrag" and not "theCrag powered by TopoGuru"?

**Comment by rouletout** [comment]
Somehow related to https://github.com/theCrag/tca/issues/19 - this is aprt of the on-going discussion and a very valid question. Branding is to be decided.

**Comment by rouletout** [comment]
The first release will be as is branded now, we keep the option open to brand the app as theCrag at a later stage
