### ISSUE TITLE
Opening topos of Bürs/Steinbruch shows topos of other sector

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#21]
Switching to tap "TOPOS" on the page of "Bürs/Steinbruch" shows topos of neighbour sector "Bürs/Rumpelkammer".

If I select to show topos of a specifc sector, just show topos ot that one. Hide other sectors.

**Comment by bkucsera** [comment]
We also saw this problem, under process, thanks for it!

**Comment by rouletout** [comment]
@lordyavin is this gone for you?

**Comment by lordyavin** [comment]
Can't confirm as I'm not able to open the crags description any more.

**Comment by rouletout** [comment]
@lordyavin can you explain this? I suggest you unisnatllö and install again. This is working fine for everyone else. Thanks

**Comment by lordyavin** [comment]
Yes this issue is gone but the topo is not properly displayed. ![Screenshot_20210223-170308.png](https://user-images.githubusercontent.com/1528540/108871121-1c7a0f80-75f9-11eb-81cf-8a344644c3f2.png)

**Comment by bkucsera** [comment]
Isnt it a download/network problem? For me it looks good.
Can you check please if you still have the problem?
![Screenshot_20210224-131158_Topo Guru](https://user-images.githubusercontent.com/78022975/108999222-e9d42380-7699-11eb-9f32-f2e6ce26026f.jpg)

**Comment by lordyavin** [comment]
Probably it is, but should not happen without feedback.
