### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#22]
The search is missing.

**Comment by bkucsera** [comment]
You can find the search function on the list view. Can you find it (or its a bug and you don't see on your device)?

**Comment by lordyavin** [comment]
Okay found the filter/search by name on the routes tab of a crag. But I miss a global simple search and the faceted search of the website. Eg. so. formular to search for routes in an area/TLC/... for routes that fit my requirements.

**Comment by bkucsera** [comment]
True, the worldwide search is a must to have. At the moment the Search is working only in that group of crags what you clicked on the World Map view.
We will change it like this:
- In the list, you will see only those crags what you see on your actual World Map. For example if you zoom in and see Tyrol only on the World Map, you will see those crags listed on the List View, what you see on the map.
- we will expand the Search to continents, so if you search for a route, crag, etc... name in the text Search, you will get every result for your actual continent.
- route difficulty search/filter is available now as well, if you click on Routes tab under Search (i guess you found it). Making the really detailed search funcionality of the website would be to messy in a mobile app i think. But this can be a discussion later, if we decide to make the mobile search smarter.

Search is ok like this? Please tell us if you have other comments on this issue.

**Comment by rouletout** [comment]
@lordyavin please comment here - we will not have advanced search in a long time in the app, but simple search should work now. Please check.

**Comment by lordyavin** [comment]
Availability of principal search is confirmed.
