### ISSUE TITLE
Sharing content 

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#24]
I tapped the link/share icon ![_20210127_092330.JPG](https://user-images.githubusercontent.com/1528540/105963497-5949f980-6081-11eb-95e9-3bde6fe2afa9.JPG) and chose the option to copy the link. Got that text:
```
Open Austria in theCrag powered Topo Guru app! 
https://thecrag.topoguru.com/map/11747227
```
1. issue is that the Android UI says "copy link" not "copy text". 
2. issue is that the link does not work
![Screenshot_20210127-092239.png](https://user-images.githubusercontent.com/1528540/105964039-fc9b0e80-6081-11eb-9cfd-66850a34bd1a.png)
3. Issue is that I expected to get a link to thecrag website.

**Comment by bkucsera** [comment]
This sharing function is only for testing, not gonna be in the live version.
Nicky asked us to insert a sharing button for easier screen sharing, if you see a bug in the app.
The link works only with the app (not with browsers).

**Comment by rouletout** [comment]
Works as designed, closing
