### ISSUE TITLE
add loading indicator

### ISSUE THREAD

**Issue by nicHoch** [theCrag/tca#25]
sometimes it is not clear if the APP waits for data to be ready from download.
the app is not blocked what is good but but often it is hard to tell if i should just wait a bit longer.

so a loading indicator would give some important feedback.

**Comment by bkucsera** [comment]
We will add a rotating status icon.

**Comment by bkucsera** [comment]
We have added a rotating status icon in Search and node Info tabs.

**Comment by rouletout** [comment]
Seems to be ok, closing for now
