### ISSUE TITLE
default route order should be by index

### ISSUE THREAD

**Issue by nicHoch** [theCrag/tca#27]
the default route order in any area should be defined by the index (api) not by grade.
For less then 10% of the routes topos are available. 
But many area can live without topos as the default route order in the index is based on (left to right or vise versa) something you can easily match if you are on the crag.
with the route order by the grade it is not possible to find any routes on the crag without topo.

also the route description in the route list would help to match and navigate without topo.

Very often you have descriptions like: 
 - same start as ....
 - follow the crag
 - left of the arete 
 - ....
also it makes no sense to combine routes from different areas/sectors.
you never climb in multiple sectors or the entire  crag at once.

**Comment by rouletout** [comment]
Yes, didn't realize this - I consider this a must fix, also, annotations are not shown, I'll create a separate issue for that.

**Comment by rouletout** [comment]
This seems fixed, @nicHoch please confirm and close if ok

**Comment by nicHoch** [comment]
The route order within a sector is good. But now the order of the routes at higher levels are merged all together in a very strange order.
First route in each sector .Second route in each sector ...

I once more would like to suggest not to mix routes from different sectors into one route list. 

![image](https://user-images.githubusercontent.com/2226714/111529258-3921e700-8762-11eb-82ec-ed8f09db958d.png)

**Comment by nicHoch** [comment]
if the combined route list is very desired then please add a section header for each sub area:

![image](https://user-images.githubusercontent.com/2226714/111529773-d4b35780-8762-11eb-96c5-0c491e5ec6f1.png)

**Comment by rouletout** [comment]
Closing here as this is in more detail in https://github.com/theCrag/tca/issues/69
