### ISSUE TITLE
Annotations not shown

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#28]
Annotations are an important way to structure the data in the index and for orientation at the cliff. They are currently not shown at all but should be visible in eg the Route List.

Open eg the crag "Häuselberg" in Austria Ost where there is one (https://www.thecrag.com/de/klettern/austria/wien-vienna-area/area/800583708#n3756660249) or Jassingau (https://www.thecrag.com/de/klettern/austria/wien-vienna-area/area/941840751)

**Comment by bkucsera** [comment]
As we see annotations are connecting to the route list. Where should we put this? What if we put it on the Info tab as a text info, between Approach info and Route stats graph?
Im not sure where it would be the most logical.

**Comment by rouletout** [comment]
No this must be shown in the route or area list as it gives strucure to the 2 (mostly route list). Look at this example on the web: https://www.thecrag.com/de/klettern/mexico/area/2676519354

**Comment by bkucsera** [comment]
Done, annotations are in the route list.
Example: Lavanttaler Alpen / Hauselberg Leoben: you can see it here in the route list

**Comment by rouletout** [comment]
Available, Closing
