### ISSUE TITLE
Map view - unintended automatic zoom out

### ISSUE THREAD

**Issue by birgander2** [theCrag/tca#30]
The map keeps on zooming out automatically to almost whole Europe once you display a region without any crag in it. I find this very annoying.

**Comment by bkucsera** [comment]
The reason for this is that we use limited database now with 3 countries. The map function automatically zooms out until it does not find nodes on the map.
With the full database there will be crags closer to your actual location, so the map will not zoom out.

**Comment by birgander2** [comment]
I'm not sure. If I zoom into really a lot in one of the available countries, but besides a crag, this zoom out to world occurs. For example sometimes I like to search around a crag for parking, trail etc.  What is the advantage of zooming out automatically?

**Comment by bkucsera** [comment]
Automatic zoom turned off, you can check it in the next beta release (probably friday)

**Comment by rouletout** [comment]
@birgander2 is this now working as expected?

**Comment by birgander2** [comment]
Yes, much better now!

**Comment by rouletout** [comment]
OK thanks, closing for now
