### ISSUE TITLE
Profile country/city is manual entry

### ISSUE THREAD

**Issue by matozoid** [theCrag/tca#33]
A drop-down could be handier,

**Comment by bkucsera** [comment]
Ok, country will be a drop-down! City remains like as it now. (It would be a big database, and its not so important at the moment for us and not a required user-info)

**Comment by matozoid** [comment]
Guessing the country based on GPS position would be even more awesome :-) Oh, and doesn't thecrag have this information? I logged in with that account.

**Comment by bkucsera** [comment]
Country based on GPS was a possibility during the development, but we decided not to use. Climbers often travel abroad and start using/downloading the app not in their country of origin. 
theCrag has the info, but we dont get this info with the API at the moment, as far as i remember.

**Comment by rouletout** [comment]
Country is pick list now, closing
