### ISSUE TITLE
Profile country defaults to UK

### ISSUE THREAD

**Issue by matozoid** [theCrag/tca#35]
I logged in with my thecrag account and found out that the country field in my profile was set to... I forgot, I think UK. I live in the Netherlands though.

**Comment by bkucsera** [comment]
We dont get Country and City info from thcrag API, so it should be empty in Topo Guru app when you register. UK is interesting, we will check it.

**Comment by rouletout** [comment]
@matozoid can you check this again please as we can't reproduce

**Comment by matozoid** [comment]
I can't do a clean new user registration because I already registered, so I can't help anymore :-(

**Comment by bkucsera** [comment]
As we don't have the data from the api, the app sets the country by the language/territory info of the device. 
So if you use english setting, it will be UK, if you use dutch language on your phone, it will be Netherlands.
Not 100% solution, but i think this is good for the first version.

Other option is we leave the country empty for every theCrag user.

**Comment by rouletout** [comment]
Closing as it is based on device settings of the user.
