### ISSUE TITLE
Offline maps should be a fundamental feature.

### ISSUE THREAD

**Issue by matozoid** [theCrag/tca#37]
Bad mobile phone reception is a given when near a crag. Having the crag data on your phone, and being able to add logs and routes should always be accessible, but it seems like it is planned to be premium?

**Comment by bkucsera** [comment]
Offline data will be available without subscription, we will put it in the next beta. 
The offline data of mapbox data will be in a later release. (We will use bounded boxes for the crag overview maps).

Btw the app caches all browsed data, so if you ever opened a crag, you are able to see the data of it even when you are offline.

**Comment by matozoid** [comment]
Great news, thanks!
