### ISSUE TITLE
Map: can't click circles

### ISSUE THREAD

**Issue by matozoid** [theCrag/tca#39]
I thought it would go to the crag in question, but it does nothing.

**Comment by rouletout** [comment]
Can you provide a screenshot please? For me this works - it opens the overview bar of the crag In question and then you can open it from there.

**Comment by matozoid** [comment]
It does what you say it does. I thought clicking the circle itself would go to the crag directly. I guess this was a conscious decision?

**Comment by rouletout** [comment]
Yes, this mimics the behaviour of the web in some way, there we also open the bubble first and only on the next click you open the crag. Makes it easier if you click by accident or look for more details before you open.

**Comment by matozoid** [comment]
If it is as intended, then this can be closed.
