### ISSUE TITLE
Add donautal to beta

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#40]
Due to corona its unlikely that I going to visit spots in Switzerland or austria. Please add my home crags to the beta that I'm able to do some real world tests.

**Comment by birgander2** [comment]
And Austria seems to be missing since the update. I hardly know any crag in Switzerland.

**Comment by bkucsera** [comment]
@scd can we add some nearby crags?
If you miss Austria, please logout and login again, it is because of the beta version. (At the live release, you will not need to logout/login again after an update on the app, it's just the beta versions)

**Comment by birgander2** [comment]
Nope, still no Austria. To be precise, almost no Austria, just the premium crags and maybe 2 or 3 regular ones in the very south.

**Comment by rouletout** [comment]
@birgander2 Austria is available for me. Can you please delete and re-install and check again?

**Comment by birgander2** [comment]
Yes, works now after I deleted all app data.

**Comment by rouletout** [comment]
Closing, this will be with first release

**Comment by lordyavin** [comment]
Until then I won't be able to do real world testing.
