### ISSUE TITLE
Missing sub-areas

### ISSUE THREAD

**Issue by birgander2** [theCrag/tca#49]
The area "Austria/Inntal/Wörgl-Kufstein" shows up (correctly) with 277 routes, but has only 2 crags listed under "Areas" with 23 routes. All the other crags are missing.

**Comment by bkucsera** [comment]
Thanks for the comment! Its good that you detected this bug, we have ask for a change in the API as well (to have the child notes as well in a TLC request). We have assigned this issue for Simon.

**Comment by murray-d** [comment]
Appears to be same issue for the 'Wollongong' region level. 623 routes but only 1 sector displayed. And in addition 1 other sector shows on the map but is not linked as a child node.

**Comment by bkucsera** [comment]
Fixed. At the moment there are only crags under Wollongong, we see the same on the web and the app:
https://www.thecrag.com/en/climbing/australia/wollongong
Please check it, if works on your side too, we can close this issue.

**Comment by rouletout** [comment]
This seems ok now, closing - there is an issue with not listing gyms (which explains the delta in routes) but showing them on the map, I'll log that as a separate issue
