### ISSUE TITLE
theCrag login

### ISSUE THREAD

**Issue by happykcz** [theCrag/tca#50]
I can't log in with my theCrag account (login name and pwd 100% correct). 
I have originally created a new TopoGuru account, thinking it would link the theCrag. As it didn't, I deleted the TopoGuru and now I can't log in with theCrag. I used the same email address for both.

**Comment by bkucsera** [comment]
Its a bug, we will fix it.
Now we have restored your email address, so you can login in the app with your theCrag profile data. Please do not delete your user for a while, until we solve this :)

**Comment by bkucsera** [comment]
solved, we can close this issue.
