### ISSUE TITLE
'Read more' button goes nowhere

### ISSUE THREAD

**Issue by happykcz** [theCrag/tca#51]
I managed to use the button 'Read more on theCrag' on the info page before everything fully loaded. It leads to the wrong page.

![Screenshot_20210216-194456_Firefox](https://user-images.githubusercontent.com/54214652/108580998-1241e200-7369-11eb-8a91-9ee52847858c.png)

**Comment by andrasbari** [comment]
Which crag do you want to see? Can you describe more?

**Comment by happykcz** [comment]
Hi Andras, sorry for such a delay reply. 
The problem is not really related to a specific crag. It does happen with any when clicking the 'Read more on theCrag' button before everything for the selected crag is fully loaded. Pls, find an example attached for the Blue Mountains. 
![Screenshot_20210313-085019_Topo_Guru](https://user-images.githubusercontent.com/54214652/111013364-0a121b00-83da-11eb-83ac-a86a5ccd19b6.png)

**Comment by rouletout** [comment]
This is weird as it works for me. Are you connected to the network?

**Comment by happykcz** [comment]
Hi,
I've got a slow connection, so it takes time for the selected crag to get fully loaded. If I click the button before it's loaded, it'll go to the 'null' address. Therefore, from my perspective, the button shouldn't be active until the page/crag is fully loaded?
Cheers

**Comment by rouletout** [comment]
@happykcz can you please retry? I'm on super slow network and can't reproduce that. If I click it just takes longer - even when the page is not yet loaded but I never get a 404.

**Comment by rouletout** [comment]
Closing as it doesn't seem to be an issue (anymore?)

**Comment by happykcz** [comment]
Hi, sorry for the late reply. 
Unfortunately, it's still happening. I've just tried with a crag I haven't look at in the app yet, Grampians. Before all info for the crag is loaded, the button goes to thecrag.com**null**. Not sure at what stage the button get the correct link, but It went to Null even when the main picture of the crag was already displayed. Once all text/description was loaded, the button worked. Hopefully this help. 
Cheers
![Screenshot_20210328-071143_Topo_Guru](https://user-images.githubusercontent.com/54214652/112737691-2fd11f80-8f97-11eb-8b18-427352b0f597.png)

**Comment by rouletout** [comment]
ok, good but not good - we will look into that.


Also consider renaming the button to "Read more and contribute on theCrag"

**Comment by andrasbari** [comment]
It will be fixed in the next release. To minimize server load and bandwith usage, the url parameter is not downloaded with the map metadatas. If you open the node info page you receive more detailed metadatas on the background. In this small time (while your mobile and the server communicates) you have an empty(null) url parameter. We switch the url generation format to this: `https://www.thecrag.com/<nodeId> ` and it will fix everything, we not need anymore to receive the url parameter at the https://www.thecrag.com/en/article/api#index-detail endpoint. So it is unneccessary in the future. Less data = faster application

**Comment by bkucsera** [comment]
Fixed (v151), please check and close if works properly.

**Comment by happykcz** [comment]
All good now, thx for the great work guys
