### ISSUE TITLE
Font type are hard to read

### ISSUE THREAD

**Issue by FROGCLIMB** [theCrag/tca#53]
Font type used fot the crag names on the map view are hard to read.
Recommend that you use a single line solid font.

![Screenshot_20210225-061739_Topo Guru](https://user-images.githubusercontent.com/79647409/109163959-1f7b1a00-7737-11eb-83c3-1bb991c3377d.jpg)

**Comment by birgander2** [comment]
+1

**Comment by bkucsera** [comment]
We are going to change to inverse colours.

**Comment by rouletout** [comment]
Looks good now, closing
