### ISSUE TITLE
Grade filter does not refresh

### ISSUE THREAD

**Issue by FROGCLIMB** [theCrag/tca#55]
The grade filter scroller appears to work ok when you move the ball to the right. But when you move the ball back to the left the climbs do not refresh
![Screenshot_20210225-062304_Topo Guru](https://user-images.githubusercontent.com/79647409/109165525-e2b02280-7738-11eb-8237-39637306c34d.jpg)
![Screenshot_20210225-062401_Topo Guru](https://user-images.githubusercontent.com/79647409/109165556-eba0f400-7738-11eb-9241-e553a371acb9.jpg)

**Comment by bkucsera** [comment]
Fixed. The "swipe to refresh" function was the reason for this, now its allowed only on the crag info page.

**Comment by rouletout** [comment]
Working, closing
