### ISSUE TITLE
Boulder area specfic sub area types not shown

### ISSUE THREAD

**Issue by nicHoch** [theCrag/tca#58]
`field `and `boulder` as area type are not supported.

https://thecrag.topoguru.com/info/722997519
this area only provides the `sector` but not `boulder` and  `field`

https://thecrag.topoguru.com/info/1033400739
this area shows no subarea at all as all subarea of type: (`field` or `boulders`)

this might also related to: https://github.com/theCrag/tca/issues/26

**Comment by bkucsera** [comment]
We will show "field" and "boulder" under sector tab for the first release.
In the second release we can find out how to visualize this better.

**Comment by rouletout** [comment]
Boulders are still not shown, check eg Zillergrund

**Comment by andrasbari** [comment]
I fixed it in the 147 (3.0.58) version.

**Comment by bkucsera** [comment]
Fixed (v151), please check and close if works properly.

**Comment by rouletout** [comment]
works, closing
