### ISSUE TITLE
sort order of topos and sub areas

### ISSUE THREAD

**Issue by nicHoch** [theCrag/tca#59]
what is the default sort order in the sub area tabs and also in the topo tab?
it sometimes looks like order by number of child routes. 
the current ordering is not very helpful the area and topo order in the index is very often based on geography (left to right, approach ...) 

example topo order: https://thecrag.topoguru.com/info/192156681

the current topo order is (based on route number): 13-21 | 22 - 26 |  11 | 2 - 10

i expect (order by index): 2 - 10 | 11 | 13-21 | 22 - 26 

example sector order: https://thecrag.topoguru.com/info/12495061

current order: Säli Kante | Power Hour | Untere Flüh | Elefant | Torwand | 
i expect (order by index): Untere Flüh | Elefant |  Säli Kante | Power Hour | Torwand | 

![image](https://user-images.githubusercontent.com/2226714/110458186-c2367f80-80cb-11eb-9612-93e61bef352f.png)

the crag is well order from west to east: but in the "sector" tab is is orders by route count.

**Comment by DaneEvans** [comment]
I noticed this one as well

**Comment by bkucsera** [comment]
We have changed the sorting method to siblings order, from route count.
What if we change this only at top level crags and under? Because in bigger areas, regions, maybe its more informative for the users to have the order by route count. What do you think? @rouletout?

**Comment by rouletout** [comment]
This shouldn't be different at different levels as this will be uncomprehensible to the user. Areas / regiopns often have sort orders that make implicit sense such as geographical arrangement, alphabetical order and such. So no, route count is not a criterion.

**Comment by bkucsera** [comment]
Ok, we do it by siblings order.

**Comment by nicHoch** [comment]
the new release does the order of the areas by index: good
the order of the topos is still "random".

**Comment by bkucsera** [comment]
Fixed, please check the next release (148).
We have positionMinLabel and positionMaxLabel values, order set by MinLabel. Is it ok like this?

**Comment by andrasbari** [comment]
in the 148 (3.0.59) version, the topos pager order was fixed. topos ordered by positionMinLabel

**Comment by rouletout** [comment]
closing
