### ISSUE TITLE
Login with local DB and Facebook only

### ISSUE THREAD

**Issue by lordyavin** [theCrag/tca#6]
Please if you want to integrate third party authentication, then provide more than the biggest brother Facebook. I vote to completely drop Facebook integration! For the sake of privacy an individual login for the crag should be sufficient.

May I ask why the form provides Facebook as third party authenticator only?

**Comment by rouletout** [comment]
Login is part of the next phase, like it or not FB is one of the biggest 3rd party authenticators and would hurt us if not being available.

**Comment by lordyavin** [comment]
That does not answer why there are not more options. Additionally I wonder if the uprising generation of climbers has a Facebook account. If third party authentication shall be available then please be diverse and provide more than Facebook.

**Comment by rouletout** [comment]
Login with theCrag account works, FB, Google, and Apple authentication possible, closing
