### ISSUE TITLE
Map lacks a "current position" icon

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#7]
When opening the map, I can't center on my current position.

**Comment by bkucsera** [comment]
Thanks for the comment, we are going to add it to the next beta release.

**Comment by bkucsera** [comment]
Fixed, next beta is out in a few hours time.

**Comment by rouletout** [comment]
I'm on 3.0.55 (144) but can't see it

**Comment by andrasbari** [comment]
@rouletout If you did not have gps in your device or did not grant location permissions, you can't see the "goto my location" icon on the bottom right of the map.
![Screenshot_20210323-142833](https://user-images.githubusercontent.com/5318705/112154303-6c41fb80-8be4-11eb-8ae0-d005abacf0c9.png)

**Comment by rouletout** [comment]
Yes, that was it :-) - closing
