### ISSUE TITLE
How to deselect an area

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#72]
This is probably just me as an Android novice. Once I click on a donut on the map the blue area is highlighted and the map zooms in. How do I get out of that again? If I click back (button) it thinks I wnat to quit the app. I have no idea what to do to deselect the previous area.

**Comment by killakalle** [comment]
I have the same issue. Cannot deselect an area/crag/whatever. The back button for me takes me to the previously selected area.

It would be nice if you could just click anywhere on the map to deselect.

**Comment by bkucsera** [comment]
It will be fixed in next release (151).

**Comment by rouletout** [comment]
works perfect, closing
