### ISSUE TITLE
area type "cliff" not suported

### ISSUE THREAD

**Issue by nicHoch** [theCrag/tca#76]
"cliffs" do not show up in the area lists.

example: https://thecrag.topoguru.com/info/11764639

the support of more and more area type (https://github.com/theCrag/tca/issues/58) will make this even worse: https://github.com/theCrag/tca/issues/26

**Comment by bkucsera** [comment]
Somewhy "Cliff" is was taken out from the tabs, we fix it soon!

**Comment by bkucsera** [comment]
Fixed (v151), please check and close if works properly.

**Comment by rouletout** [comment]
works, closing
