### ISSUE TITLE
Markup not interpreted 

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#9]
In the description for Zillertal we use :gb: and :de: to mark text in the respective languages (with flags). The app shows the uninterpreted markup text.

**Comment by bkucsera** [comment]
We will fix it. 
Do you know if you use "ISO 639-1" for the country codes on the web? @scd

**Comment by andrasbari** [comment]
> We will fix it.
> Do you know if you use "ISO 639-1" for the country codes on the web? @scd

I saw this in the english description: :gb: 
It seems to be "ISO 3166 alpha-2" or something else? Please describe it. @scd

**Comment by scd** [comment]
Actually this is emoji handling which is `:emoji:` or a shorthand equivalent.

```
%CIDS::Application::Emoji::Shorthand = (
  ":)" => 'smiley',
  # ":-" => 'smiley', # does not work
  ":-)" =>'smiley',
  ":(" => 'cry',
  ":D" => 'grinning',
  ":P" => 'stuck_out_tongue',
  ":O" => 'open_mouth',
  ":|" => 'expressionless',
  ":/" => 'confused',
  ";)" => 'wink',
  ";P" => 'stuck_out_tongue_winking_eye',
  "<3" => 'heart',
);
```

```
%CIDS::Application::Emoji::CopyAndPasteFromTwemojiAwesome = (
  "1f604" => "smile",
  "1f606" => "laughing",
  "1f60a" => "blush",
...
   "1f1ef-1f1f5" => "jp",
  "1f1f0-1f1f7" => "kr",
  "1f1e8-1f1f3" => "cn",
  "1f1fa-1f1f8" => "us",
  "1f1eb-1f1f7" => "fr",
  "1f1ea-1f1f8" => "es",
  "1f1ee-1f1f9" => "it",
  "1f1f7-1f1fa" => "ru",
  "1f1ec-1f1e7" => "gb",
  "1f1e9-1f1ea" => "de",
...
```

As the variable suggests we copied and pasted from the repository of Twemoji Awesome

**Comment by rouletout** [comment]
Still the same

**Comment by andrasbari** [comment]
@scd Can you upload the actually used translate table? I think we need to convert twemojis to utf8mb4 values. In the description we did not use webview or something else. We convert the html source to spannable text. Android support utf8 emojis, so we need to convert the text to utf8 characters. I need that translate table which is used on the thecrag website too.

**Comment by andrasbari** [comment]
emoji test results in the app:

![Screenshot_20210324-091612](https://user-images.githubusercontent.com/5318705/112277132-ba590c80-8c81-11eb-8476-4b4259dac787.png)

**Comment by andrasbari** [comment]
![Screenshot_20210324-091601](https://user-images.githubusercontent.com/5318705/112277541-29cefc00-8c82-11eb-84a8-d41bec51f77e.jpg)

**Comment by andrasbari** [comment]
in the next release the emojis will be active in descriptions

**Comment by rouletout** [comment]
Emojis are partially shown now but not all of the mark-up is interpreted:

1) Hyperlinks do not work (eg go to "Datca" (crag) and look at the top line in the description on the web and on the app). 

2) Same is true for internal links (same text, see bluw links on web, none of them work on the app)

3) Users are not interpretd (@.....) - see history section of Datca as an example

4) Line breaks seem not to be interpreted which makes a lot of the text hard to read (you may also check Zillertal for that)

5) Parking icon is not shown instead there is a light blue square - see area "Indian Man" under Datca as an example. 

6) The GPS coordiantes from the parking (or any other) are not clickable and thus do not open in the navigation app

**Comment by rouletout** [comment]
A good test case is Czech Republic as well (https://www.thecrag.com/de/klettern/czech-republic). Closing, only users not working - created separate issue for this.
