### ISSUE TITLE
Cannot navigate to children

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#91]
**What happened?**
Go to Alzira. Try to navigate to one of the children, e.g. Tallat Roig. 
However, children are not listed. 

Example url(s) to reproduce the problem:
Open Alzira (Crag) in theCrag powered Topo Guru app! 
https://thecrag.topoguru.com/info/4179649881

Ideally also provide screenshots:
![Screenshot_20210407_152841_com topoguru](https://user-images.githubusercontent.com/30682796/113874724-5fadcd80-97b6-11eb-8038-1153fe6d5713.jpg)

**What you expected:**

* [ ] Can navigate to children other than searching for them on the map
* [ ] List of Children visible somewhere

**Comment by rouletout** [comment]
This is a known issue as it is not displaying "cliffs" right now - will be fixed in next release, see https://github.com/theCrag/tca/issues/76

**Comment by killakalle** [comment]
Similar issue for

https://thecrag.topoguru.com/info/2912893242

Children are artificial areas

**Comment by killakalle** [comment]
Looks fixed. Closing.
