### ISSUE TITLE
Route grades not shown on topo page

### ISSUE THREAD

**Issue by rouletout** [theCrag/tca#92]
**What happened?**

Open Mexico / Chiapas / San Cristobal / El Arcotete and go to teh topo page. For example "El Arcotete" shows 11 routes but no grades in the list below.

Ideally also provide screenshots:

**What you expected:**

Route list with grades and detail info.

**Comment by bkucsera** [comment]
We have made modificiatons in the api calls, it will work well in v151.

**Comment by rouletout** [comment]
works, closing
