### ISSUE TITLE
Tag description redundant

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#95]
**What happened?**
Tag descriptions are next to tags, that's redundant and consumes a lot of space

Example url(s) to reproduce the problem:
Open Setas en el Parque Central (Artificial) in theCrag powered Topo Guru app! 
https://thecrag.topoguru.com/info/2912905038

Ideally also provide screenshots:
![Screenshot_20210408_232710_com topoguru](https://user-images.githubusercontent.com/30682796/114098843-3b3f1780-98c2-11eb-8253-8ed2da804279.jpg)

**What you expected:**

* [ ] Show Tags only - without descriptions
* [ ] Nice-to-have: Show tag description only when clicking a tag or sth like that

**Comment by rouletout** [comment]
Text will be removed

**Comment by bkucsera** [comment]
Text will be removed in all cases where we have an icon.

**Comment by bkucsera** [comment]
Fixed, please check and close.
Or we can re-label this as an Enhancement, for this suggestion: "Nice-to-have: Show tag description only when clicking a tag or sth like that"

**Comment by killakalle** [comment]
Looks fine. Closing.
