### ISSUE TITLE
theCrag link does not work

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#97]
**What happened?**
Go to Xulo Panderas, click theCrag link. the Crag opens on regular dashboard (
https://www.thecrag.com/) 

Example url(s) to reproduce the problem:

Open Xulo Panderas (Sector) in theCrag powered Topo Guru app! 
https://thecrag.topoguru.com/info/1403873091
Ideally also provide screenshots:

**What you expected:**

* [ ] Xulo Panderas opens on theCrag

**Comment by rouletout** [comment]
@killakalle can you please check again?

**Comment by killakalle** [comment]
Works. Closing
